# Imagen base
FROM node:18

# Crear carpeta de la app
WORKDIR /app

# Copiar los archivos
COPY . .

# Instalar dependencias
RUN npm install

# Exponer el puerto (solo si tu app escucha un puerto)
EXPOSE 3000

# Comando para ejecutar la app
CMD ["node", "index.js"]
